// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using template_csharp_reviews_site;

namespace template_csharp_reviews_site.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220215213643_reviews")]
    partial class reviews
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("template_csharp_reviews_site.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OSVer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Samsung",
                            Model = "Galaxy",
                            OSVer = "Android 10",
                            Price = 800.0,
                            ReleaseDate = new DateTime(2022, 2, 15, 16, 36, 42, 439, DateTimeKind.Local).AddTicks(2730)
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Apple",
                            Model = "iPhone 13 Pro Max",
                            OSVer = "iOS",
                            Price = 1099.0,
                            ReleaseDate = new DateTime(2022, 2, 15, 16, 36, 42, 449, DateTimeKind.Local).AddTicks(1317)
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Motorola",
                            Model = "Razr",
                            OSVer = "Android 9",
                            Price = 499.0,
                            ReleaseDate = new DateTime(2022, 2, 15, 16, 36, 42, 449, DateTimeKind.Local).AddTicks(1594)
                        },
                        new
                        {
                            Id = 4,
                            Brand = "GooglePhone",
                            Model = "Pixel 6 Pro",
                            OSVer = "Android 12",
                            Price = 599.0,
                            ReleaseDate = new DateTime(2022, 2, 15, 16, 36, 42, 449, DateTimeKind.Local).AddTicks(1625)
                        });
                });

            modelBuilder.Entity("template_csharp_reviews_site.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "I love it.",
                            ProductId = 1,
                            Rating = 5,
                            ReviewDate = new DateTime(2022, 2, 15, 16, 36, 42, 449, DateTimeKind.Local).AddTicks(2688),
                            Title = "Great.",
                            UserName = "Lisa"
                        },
                        new
                        {
                            Id = 2,
                            Content = "I love it.",
                            ProductId = 2,
                            Rating = 5,
                            ReviewDate = new DateTime(2022, 2, 15, 16, 36, 42, 449, DateTimeKind.Local).AddTicks(5393),
                            Title = "Great.",
                            UserName = "Norm"
                        },
                        new
                        {
                            Id = 3,
                            Content = "I love it.",
                            ProductId = 3,
                            Rating = 5,
                            ReviewDate = new DateTime(2022, 2, 15, 16, 36, 42, 449, DateTimeKind.Local).AddTicks(5574),
                            Title = "Great.",
                            UserName = "Chaz"
                        },
                        new
                        {
                            Id = 5,
                            Content = "I love it.",
                            ProductId = 1,
                            Rating = 5,
                            ReviewDate = new DateTime(2022, 2, 15, 16, 36, 42, 449, DateTimeKind.Local).AddTicks(5605),
                            Title = "Great.",
                            UserName = "Donna"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
