// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using template_csharp_reviews_site;

namespace template_csharp_reviews_site.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("template_csharp_reviews_site.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OSVer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Samsung",
                            Model = "Galaxy",
                            OSVer = "Android 10",
                            Price = 800.0,
                            ReleaseDate = new DateTime(2022, 2, 14, 19, 11, 33, 866, DateTimeKind.Local).AddTicks(8763)
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Apple",
                            Model = "iPhone 13 Pro Max",
                            OSVer = "iOS",
                            Price = 1099.0,
                            ReleaseDate = new DateTime(2022, 2, 14, 19, 11, 33, 873, DateTimeKind.Local).AddTicks(2285)
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Motorola",
                            Model = "Razr",
                            OSVer = "Android 9",
                            Price = 499.0,
                            ReleaseDate = new DateTime(2022, 2, 14, 19, 11, 33, 873, DateTimeKind.Local).AddTicks(2447)
                        },
                        new
                        {
                            Id = 4,
                            Brand = "GooglePhone",
                            Model = "Pixel 6 Pro",
                            OSVer = "Android 12",
                            Price = 599.0,
                            ReleaseDate = new DateTime(2022, 2, 14, 19, 11, 33, 873, DateTimeKind.Local).AddTicks(2474)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
